name: Network Automation

on: [push]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Debug - show files
      run: |
        pwd
        ls -l

    - name: Install Ansible
      run: |
        python3 -m pip install --upgrade pip
        pip3 install ansible

    - name: Check Ansible version
      run: ansible --version

    - name: Run Playbook
      run: |
        ansible-playbook -i inventory.ini playbook.yml

#new