name: Network Automation

on: [push]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup environment
      run: |
        python3 -m venv ansible-env
        ansible-env/bin/pip install --upgrade pip
        ansible-env/bin/pip install ansible paramiko
        ansible-env/bin/ansible-galaxy collection install cisco.ios

    - name: Create Vault Password File
      run: |
        echo "${{ secrets.VAULT_PASS }}" > vault_pass.txt
        chmod 600 vault_pass.txt

    - name: Run Playbook
      run: |
        ansible-env/bin/ansible-playbook -i inventory.ini playbook.yml --vault-password-file vault_pass.txt