name: Network Automation

on: [push]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup environment
      run: |
        python3 -m venv ansible-env
        source ansible-env/bin/activate
        pip install --upgrade pip
        pip install ansible paramiko
        ansible-galaxy collection install cisco.ios

    - name: Create Vault Password File
      run: echo "${{ secrets.VAULT_PASS }}" > vault_pass.txt

    - name: Run Playbook
      run: |
        source ansible-env/bin/activate
        ansible-playbook -i inventory.ini playbook.yml --vault-password-file vault_pass.txt